name: "Prepare test environment"
description: "Prepares test environment"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '${{ env.GO_VERSION }}'

    - name: Setup Mage
      run: |
        git clone https://github.com/magefile/mage
        cd mage
        go run bootstrap.go
      shell: bash

